server:
  port: 8001
  servlet:
    context-path: /member
spring:
  datasource:
    url: jdbc:mysql://rm-uf66o0e3fbbqaqk41wo.rwlb.rds.aliyuncs.com:3306/train_member
    username: train_member
    password: Xiao_guan666
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com:
      xiaoguan:
        train:
          member:
            mapper: trace