server:
  port: 8000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            max-age: 3600
      routes:
        - id: member
          uri: lb://member
          predicates:
            - Path=/member/**
        - id: business
#          uri: http://127.0.0.1:8002
          uri: lb://business
          predicates:
            - Path=/business/**
        - id: batch
#          uri: http://127.0.0.1:8003
          uri: lb://batch
          predicates:
            - Path=/batch/**

