server:
  port: 8002
  servlet:
    context-path: /business
spring:
  application:
    name: business
  datasource:
    url: jdbc:mysql://localhost:3306/train_business?serverTimezone=Asia/Shanghai
    username: train_business
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
      port: 6379
      password: Redis000
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      cache-null-values: false
      time-to-live: 5s
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    local-cache-scope: statement
logging:
  level:
    com:
      xiaoguan:
        train:
          business:
            mapper: trace


